### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'xxxxxxx/0.data_prepare

### ISSUE THREAD

**Issue by CTLife** [YY-TMU/InPACT#2]
**can not run InPACT:**

InPACT   -i ../0_BAM.2PASS/Input/mRNA_SRR8462062_GSM3572799_NA18498_Input.bam    -a hg38.109.20211119.ncbiRefSeq.gtf    -s  InPACT_polyAsites.hg38.saf    -P 8    -paired False

------------------------------------------------------------------------------------------------------------------------------
2024.03.30 15:26        Start    ../0_BAM.2PASS/Input/mRNA_SRR8462062_GSM3572799_NA18498_Input.bam
Prepare annotation files
2024-03-30 15:26: #########################Start : Date preparation#########################
Traceback (most recent call last):
  File "/home/yp/.conda/envs/InPACT/bin/InPACT_annotation_prepare", line 335, in <module>
    createDir(save_dir)
  File "/home/yp/.conda/envs/InPACT/bin/InPACT_annotation_prepare", line 26, in createDir
    os.mkdir(dir_file)
FileNotFoundError: [Errno 2] No such file or directory: 'mRNA_SRR8462062_GSM3572799_NA18498_Input/0.data_prepare'

**Comment by CTLife** [comment]
I created folder  mRNA_SRR8462062_GSM3572799_NA18498_Input,  no this error.

**But generated new error:**
Build model
2024-03-30 15:49: #########################Start : Training model#########################
2024-03-30 15:49: Parameters:
2024-03-30 15:49: Namespace(random_seed=888, sample_dir='mRNA_SRR8462062_GSM3572799_NA18498_Input', save_composite_model='composite.terminal.exon.model.pkl', save_dir='read_model', save_skip_model='skip.terminal.exon.model.pkl', train_fraction=0.8)
2024-03-30 15:49: ------------------------------
2024-03-30 15:49: Processing skip...
2024-03-30 15:49: Test number : 798
2024-03-30 15:49: Rest number : 10157
Traceback (most recent call last):
  File "/home/yp/.conda/envs/InPACT/bin/InPACT_read_train_model", line 219, in <module>
    ml_skip = buildModel(rt_rest_skip,random_seed)
  File "/home/yp/.conda/envs/InPACT/bin/InPACT_read_train_model", line 91, in buildModel
    ml.fit(rt_train_x,rt_train_y)
  File "/home/yp/.conda/envs/InPACT/lib/python3.8/site-packages/imblearn/ensemble/_bagging.py", line 321, in fit
    return self._fit(X, y, self.max_samples, sample_weight=None)
  File "/home/yp/.conda/envs/InPACT/lib/python3.8/site-packages/sklearn/ensemble/_bagging.py", line 337, in _fit
    max_features = self.max_features * self.n_features_in_
AttributeError: 'BalancedBaggingClassifier' object has no attribute 'n_features_in_'

**Comment by liuxc1995** [comment]
Hi,
Thanks for your question.
We have updated the InPACT script to automatically create the required directory, addressing the first question.
Regarding the second question, it may be related to the scikit-learn package. Our tests with scikit-learn version 0.24.2 didn't show any issues. 
Please try reinstalling InPACT to address these concerns.
Thank you,
Liu
